apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # Base64 encoded "postgres"
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=  # Base64 encoded "admin"
